### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by izgeri**
Add note about v5 EE / v1 OSS support.

### CODE REVIEW

**Comment by dustinmm80** [comment]
I don't think we need this disclaimer anymore, since you can deploy v5 enterprise with these scripts.

I think we should add basic instructions + link for installing conjur-oss helm chart in cyberark/conjur README. https://github.com/cyberark/conjur-oss-helm-chart

@izgeri what do you think?

**Comment by jtuttle** [comment]
@dustinmm80 Sounds like we might want to make this change after all (though remove the v5 enterprise part) as Dustin Byrne wasn't aware that the demo scripts were enterprise only. Might as well make it explicit everywhere.

**Comment by izgeri** [comment]
@dustinmm80 it would be nice to have instructions for OSS deployments

@jtuttle do you want to update the PR to link to some other existing docs for how to deploy v1 OSS? alternatively, I can open a separate issue for that.

**Comment by jtuttle** [comment]
Sure, I'll update it.

**Pull request merged**
